### ISSUE TITLE
sinceId and untilId are disabled

### ISSUE THREAD

**Issue by ibrokemypie** [ibrokemypie/mastalab#2]
havent looked at them yet, so for now all requests are without them as they did not work

**Comment by ghost** [comment]
Is it still an issue? I was able to use them without problem?
https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/client/API.java#L1050-L1061

And the POST call is simplified:
https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/client/HttpsConnection.java#L421

**Comment by ibrokemypie** [comment]
i think this prevents scrolling further down the timeline as every timeline call returns just the latest timeline, this also breaks the public timelines and such i think?

**Comment by ghost** [comment]
It works perfectly on mastalab (Misskey timeline), the scroll down fetch earlier toots.
You need to use this trick for settings max_id and since_id:

https://github.com/stom79/mastalab/blob/develop/app/src/main/java/fr/gouv/etalab/mastodon/client/API.java#L1068-L1071

**Comment by ibrokemypie** [comment]
not really sure how to implement this, as it is common for almost all requests

just using it for the home timeline seems to result in an invalid  untilId being used, causing the app to fail to load the timeline the first time (refreshing works)


line 783-803
```
    private APIResponse getHomeTimeline(String max_id, String since_id, String min_id, int limit) {

        JSONObject params = new JSONObject();
        try {
            if( max_id != null)
                params.put("untilId",max_id);
            if (0 > limit || limit > 80)
                limit = 80;
            params.put("limit", limit);
        } catch (JSONException e) {
            e.printStackTrace();
        }
        statuses = new ArrayList<>();
        try {
            HttpsConnection httpsConnection = new HttpsConnection(context);
            String response = httpsConnection.post(getAbsoluteUrl("/notes/timeline"), 60, params, prefKeyOauthTokenT);
            statuses = parseStatuses(context, new JSONArray(response), instance);
            if( statuses != null && statuses.size() > 0){
                apiResponse.setSince_id(statuses.get(0).getId());
                apiResponse.setMax_id(statuses.get(statuses.size() -1).getId());
            }
```


also, since and min id arent used

**Comment by ghost** [comment]
> causing the app to fail to load the timeline the first time (refreshing works)

This was due to a piece of code not fully disabled. It's fixed in https://github.com/ibrokemypie/mastalab/pull/39/commits/73600a9592001050dd5baed9ab64745a07a59d45

**Comment by ibrokemypie** [comment]
leaving this open as notifications and messages/mentions still dont load further down

**Comment by ibrokemypie** [comment]
Not 100% what I am doing here, just feeling around
Pagination still doesnt seem to work in notifications
